---
 - name: "update apt packages."
   become: true
   apt:
     update_cache: yes
     cache_valid_time: 86400

 - name: "upgrade packages"
   become: true
   apt:
     upgrade: yes

 - name: "Install npm and nodejs"
   become: true
   apt:
    name: ["npm", "nodejs"]
    state: latest
    update_cache: yes

 - name: Install the nodejs
   become: yes
   apt:
     name: nodejs
     state: present

 - name: "install pm2"
   become: yes
   npm:
     name: pm2
     global: yes
     production: yes
     state: present